In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 


df = pd.read_csv('../data/meningitis.csv')
display(df)

,casenum,year,month,age,race,sex,dx,priordx,priorrx,wbc,...,pr2,reds2,whites2,polys2,lymphs2,monos2,others2,sumbands,subset,abm
0,1,78.0,1.0,4.0,black,female,1.0,0.0,0.0,6.500000,...,46.0,1.0,47.0,0.0,100.0,0.0,0.0,2.000000,test,1.0
1,2,78.0,12.0,1.0,black,male,1.0,0.0,0.0,3.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.099000,training,1.0
2,3,78.0,3.0,0.8,black,male,0.0,1.0,1.0,NaN,...,51.0,335.0,230.0,0.0,100.0,0.0,0.0,NaN,test,NaN
3,4,78.0,8.0,54.0,black,male,6.0,2.0,0.0,7.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.108999,training,1.0
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,test,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,577,70.0,7.0,2.0,black,female,3.0,0.0,0.0,4.900000,...,NaN,NaN,6.0,0.0,100.0,0.0,0.0,NaN,test,1.0
577,578,70.0,7.0,23.0,black,male,4.0,0.0,0.0,10.599999,...,NaN,0.0,332.0,0.0,100.0,0.0,0.0,NaN,training,0.0
578,579,70.0,8.0,8.0,black,male,4.0,0.0,0.0,15.099999,...,NaN,NaN,28.0,0.0,100.0,0.0,0.0,NaN,test,0.0
579,580,70.0,7.0,1.0,black,female,0.0,0.0,1.0,11.599999,...,22.0,NaN,5.0,0.0,100.0,0.0,0.0,NaN,training,NaN
580,581,70.0,7.0,13.0,white,male,6.0,2.0,1.0,12.500000,...,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,test,1.0

In [3]:
print(df.info)
display(df.head())
print(df.isna().sum())
display(df['abm'].value_counts(dropna=False))

<bound method DataFrame.info of      casenum  year  month   age   race     sex   dx  priordx  priorrx  \
0          1  78.0    1.0   4.0  black  female  1.0      0.0      0.0
1          2  78.0   12.0   1.0  black    male  1.0      0.0      0.0
2          3  78.0    3.0   0.8  black    male  0.0      1.0      1.0
3          4  78.0    8.0  54.0  black    male  6.0      2.0      0.0
4          5   NaN    NaN   NaN    NaN     NaN  NaN      NaN      NaN
..       ...   ...    ...   ...    ...     ...  ...      ...      ...
576      577  70.0    7.0   2.0  black  female  3.0      0.0      0.0
577      578  70.0    7.0  23.0  black    male  4.0      0.0      0.0
578      579  70.0    8.0   8.0  black    male  4.0      0.0      0.0
579      580  70.0    7.0   1.0  black  female  0.0      0.0      1.0
580      581  70.0    7.0  13.0  white    male  6.0      2.0      1.0

           wbc  ...   pr2  reds2  whites2  polys2  lymphs2  monos2  others2  \
0     6.500000  ...  46.0    1.0     47.0     0.0    100.0     0.0      0.0
1     3.700000  ...   NaN    NaN      NaN     NaN      NaN     NaN      NaN
2          NaN  ...  51.0  335.0    230.0     0.0    100.0     0.0      0.0
3     7.500000  ...   NaN    NaN      NaN     NaN      NaN     NaN      NaN
4          NaN  ...   NaN    NaN      NaN     NaN      NaN     NaN      NaN
..         ...  ...   ...    ...      ...     ...      ...     ...      ...
576   4.900000  ...   NaN    NaN      6.0     0.0    100.0     0.0      0.0
577  10.599999  ...   NaN    0.0    332.0     0.0    100.0     0.0      0.0
578  15.099999  ...   NaN    NaN     28.0     0.0    100.0     0.0      0.0
579  11.599999  ...  22.0    NaN      5.0     0.0    100.0     0.0      0.0
580  12.500000  ...   NaN    2.0      0.0     NaN      NaN     NaN      NaN

     sumbands    subset  abm
0    2.000000      test  1.0
1    3.099000  training  1.0
2         NaN      test  NaN
3    5.108999  training  1.0
4         NaN      test  0.0
..        ...       ...  ...
576       NaN      test  1.0
577       NaN  training  0.0
578       NaN      test  0.0
579       NaN  training  NaN
580       NaN      test  1.0

[581 rows x 43 columns]>

,casenum,year,month,age,race,sex,dx,priordx,priorrx,wbc,...,pr2,reds2,whites2,polys2,lymphs2,monos2,others2,sumbands,subset,abm
0,1,78.0,1.0,4.0,black,female,1.0,0.0,0.0,6.5,...,46.0,1.0,47.0,0.0,100.0,0.0,0.0,2.000000,test,1.0
1,2,78.0,12.0,1.0,black,male,1.0,0.0,0.0,3.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.099000,training,1.0
2,3,78.0,3.0,0.8,black,male,0.0,1.0,1.0,NaN,...,51.0,335.0,230.0,0.0,100.0,0.0,0.0,NaN,test,NaN
3,4,78.0,8.0,54.0,black,male,6.0,2.0,0.0,7.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.108999,training,1.0
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,test,0.0

casenum       0
year         72
month        81
age          81
race         85
sex          81
dx           83
priordx     113
priorrx     108
wbc         141
pmn         146
bands       153
compns      295
daysrx      321
offrx       409
lptodc      414
lpgap       438
morelabs    483
bloodgl     258
gl          129
pr          249
reds        271
whites      101
polys       132
lymphs      162
monos       165
others      164
gram        313
culture     307
cie         509
bloodclt    434
bloodgl2    459
gl2         313
pr2         358
reds2       331
whites2     274
polys2      305
lymphs2     310
monos2      314
others2     316
sumbands    416
subset        0
abm          80
dtype: int64

abm
0.0    284
1.0    217
NaN     80
Name: count, dtype: int64